name: Build

on:
  push:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Project
        uses: threeal/cmake-action@v2

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build-artifacts
          path: build/bin
