name: Build

on:
  push:

jobs:
  build-project:
    name: Build Project
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Project
        uses: threeal/cmake-action@v2
        with:
          options: |
            CMAKE_BUILD_TYPE=${{ matrix['build-type'] }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build-${{ matrix.build-type }}-${{ matrix.os }}
          path: build/bin
